use std::env;
use std::fs;
use std::path::Path;
use std::f64::consts::PI;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");

    // Number of sides for the n-gon. Can be overridden with NGON_SIDES env var.
    let n_sides: usize = env::var("NGON_SIDES")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(64);

    let n_sides = if n_sides < 3 { 3 } else { n_sides };

    // compute perimeter points (unit circle)
    let mut pts: Vec<(f64, f64)> = Vec::with_capacity(n_sides);
    for i in 0..n_sides {
        let theta = 2.0 * PI * (i as f64) / (n_sides as f64);
        pts.push((theta.cos(), theta.sin()));
    }

    // Build triangle-list vertices by triangulating the perimeter using the
    // first perimeter vertex as the anchor (standard polygon triangulation).
    // Each triangle: pts[0], pts[i+1], pts[i+2] for i in 0..n_sides-2
    let mut triangles: Vec<(f64, f64)> = Vec::with_capacity((n_sides - 2) * 3);
    for i in 0..(n_sides - 2) {
        // anchor (first perimeter vertex)
        triangles.push(pts[0]);
        // first perimeter
        triangles.push(pts[i + 1]);
        // second perimeter
        triangles.push(pts[i + 2]);
    }

    // Generate Rust source
    let mut out = String::new();
    out.push_str("// This file is @generated by build.rs\n");
    out.push_str("// It provides `const VERTICES: &[Vertex]` as a triangle-list for an n-gon.\n\n");
    out.push_str("const VERTICES: &[Vertex] = &[\n");
    for (x, y) in triangles {
        // format as f32 literals for consistency with Vertex
        out.push_str(&format!("    Vertex {{ position: [{:.6}f32, {:.6}f32, 0.0f32] }},\n", x as f32, y as f32));
    }
    out.push_str("];\n");

    let dest_path = Path::new(&out_dir).join("generated_vertices.rs");
    fs::write(&dest_path, out).expect("Unable to write generated vertices");
}
